Add initial components and services to project
PishnenkoDenis/AngularUsersTest pull request #1
Opened 2024-01-31 13:36 UTC by PishnenkoDenis

Добавлены начальные компоненты Useres, Post, Filters, Select и сервисы для получения пользователей и постов: UsersService и PostsService

2024-01-31 14:34 UTC, s-skubedin requested changes

2024-01-31 14:34 UTC, s-skubedin commented on src/app/services/users/posts.service.ts
> +  postsUrl = 'https://dummyjson.com/posts';
API должен быть в env

2024-01-31 14:34 UTC, s-skubedin commented on src/app/services/users/posts.service.ts
> +  postsUrl = 'https://dummyjson.com/posts';
Вынеси домен в baseUrl (interceptor)

2024-01-31 14:34 UTC, s-skubedin commented on src/app/components/users/users.component.ts
> +      .subscribe((result: any) => (this.users = result.users));
Не используй any!

2024-01-31 14:34 UTC, s-skubedin commented on src/app/components/users/users.component.ts
> +      .subscribe((result: any) => (this.users = result.users));
Добавь обработку ошибок. Достаточно заглушки на первое время. Отдельным PR сделаешь отрисовку ошибок

2024-01-31 14:34 UTC, s-skubedin commented on src/app/components/select/select.component.html
> +<select #select name="" id="" (change)="changeTag(select.value)">
Зачем тут пустые атрибуты?

2024-01-31 14:34 UTC, s-skubedin commented on src/app/components/filters/filters.component.ts
> +  ];
Отдельным PR необходимо будет сделать логику вычленения тегов из постов

2024-02-01 11:58 UTC, PishnenkoDenis commented on src/app/components/select/select.component.html
> +<select #select name="" id="" (change)="changeTag(select.value)">
исправил

2024-02-01 12:02 UTC, PishnenkoDenis commented on src/app/components/users/users.component.ts
> +      .subscribe((result: any) => (this.users = result.users));
исправил.

2024-02-01 12:06 UTC, PishnenkoDenis commented on src/app/services/users/posts.service.ts
> +  postsUrl = 'https://dummyjson.com/posts';
Вынес в environment. .env не получается, procces не видит в файлах

2024-02-01 12:06 UTC, PishnenkoDenis commented on src/app/services/users/posts.service.ts
> +  postsUrl = 'https://dummyjson.com/posts';
Вынес в environment.

2024-02-01 12:09 UTC, PishnenkoDenis commented on src/app/components/users/users.component.ts
> +      .subscribe((result: any) => (this.users = result.users));
А что использовать?

2024-02-01 12:27 UTC, PishnenkoDenis commented on src/app/components/filters/filters.component.ts
> +  ];
Ок.Понял

2024-02-01 13:19 UTC, PishnenkoDenis commented on src/app/components/users/users.component.ts
> +      .subscribe((result: any) => (this.users = result.users));
объект user содержит множество полей, что весь этот объект типизировать?

2024-02-01 14:00 UTC, merged